language: node_js
os:
  - windows
  - linux
node_js:
  - 12
  - 10
  - 8
cache: npm
before_script: |
  if [[ "${TRAVIS_OS_NAME}" == "windows" ]]; then
    git config core.symlinks true
    git reset --hard
  fi
after_success: npx codecov --file=./coverage/lcov.info
